name: Helm publish

# run only manually
on:
  workflow_dispatch:

jobs:
  lint:
    name: Lint & Test Helm Chart
    runs-on: [self-hosted]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v4

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.6.1

      - name: Run chart-testing lint
        run: ct lint --config .github/ct.yaml

      - name: Run chart-testing install
        run: ct install --config .github/ct.yaml

  release:
    name: Release
    runs-on: [self-hosted]
    needs: lint
    permissions:
      contents: read
      packages: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v4

      - name: Get chart version
        id: chart_version
        run: |
          VERSION=$(grep '^version:' charts/podinfo/Chart.yaml | awk '{print $2}')
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Chart version: $VERSION"

      - name: Package Helm chart
        run: |
          helm package charts/podinfo
          echo "Packaged chart: podinfo-${{ steps.chart_version.outputs.version }}.tgz"

      - name: Checkout helm-charts repository
        uses: actions/checkout@v4
        with:
          repository: glavien/helm-charts
          ref: gh-pages
          path: helm-charts-repo
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Copy packaged chart to helm-charts repo
        run: |
          mkdir -p helm-charts-repo/charts
          cp podinfo-${{ steps.chart_version.outputs.version }}.tgz helm-charts-repo/charts/
          
      - name: Update Helm repository index
        run: |
          cd helm-charts-repo/charts
          helm repo index . --url https://glavien.github.io/helm-charts/charts/
          
      - name: Commit and push to helm-charts repository
        run: |
          cd helm-charts-repo
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Add podinfo chart version ${{ steps.chart_version.outputs.version }}"
          git push

      - name: Summary
        run: |
          if [ "${{ env.skip_upload }}" = "true" ]; then
            echo "✅ Chart version ${{ steps.chart_version.outputs.version }} already exists in repository"
          else
            echo "✅ Chart version ${{ steps.chart_version.outputs.version }} uploaded successfully to https://github.com/glavien/helm-charts"
            echo "📦 Chart URL: https://glavien.github.io/helm-charts/podinfo-${{ steps.chart_version.outputs.version }}.tgz"
          fi
